name: Build and Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4

    - name: setup node
      uses: actions/setup-node@v2
      with:
        node-version: '18'
      
    - name: install dependencies
      run: npm install

    - name: create build
      run: npm run build

    - name: deploy
      run: npm run ci
